name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Build
      - run: npm install
      - run: npm run build
      # Upload build file to the releas as an asset.
      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /home/runner/work/floor3d-card/floor3d-card/dist/floor3d-card.js
          asset_name: floor3d-card.js
          tag: ${{ github.ref }}
          overwrite: true
